---
k3s_version: v1.26.3+k3s1
ansible_user: pi
systemd_dir: /etc/systemd/system
k3s_server_location: /mnt/usb1/k3s
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--default-local-storage-path /mnt/usb1/k3s-pv"
extra_agent_args: ""
